### ISSUE TITLE
support for client certificates

### ISSUE THREAD

**Issue by guzzisti** [blmayer/astro#10]
Have you ever considered implementing support for client certificates for authenticating on capsules like Astrobotany or Martin Rue's Station?

I did a quick test and i't should possible without too much hassle. 
My proposal:
- allow a single cert by (sub)domain, automatically selected by astro
- store certs in `.config/astro/certs` in PEM format (crt and key file separate) named by (sub)domain, e.g. `example.com.crt` and `example.com.key`
- if a request requires a cert
  - check if the cert for this (sub)domain is already there 
  - if so repeat the request with the cert: `openssl s_client ... -cert <crt> -key <key>`
  - otherwise print instructions on how to create a cert with openssl, e.g.: `openssl req -x509 -newkey rsa:4096 -keyout ~/.config/astro/certs/example.com.key -out ~/.config/astro/certs/example.com.crt -days 36500 -nodes`

We could even create the cert ourselves if need be.

This is essentially how client certs are currently handled in gmni/cgmnlm and it works quite well.

**Comment by blmayer** [comment]
Hello again!

I thought about client certificates but never found a capsule that requested certs, so I did not implement it. 

I like your proposal, you can go ahead and submit a PR if you want, surely this will be of great value for the project.

And thanks again.
