### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by shakna-israel** [blmayer/astro#16]
Instead of using `cp`, you could use the coreutil [`install`](https://man.openbsd.org/install), which can make sure permissions are done correctly, and exists to do exactly this:

    install -m +x astro -d $(PREFIX)

It will set the mode (by the `-m` flag), ensure that the destination directories exist (`-d`, so you can install to nested ones that don't exist yet), it'll preserve any file flags, it'll set the correct user/group IDs when sudo is invoked, it'll be a no-op if the destination file is the same as the one being installed, and on Linux, it'll preserve any SELinux context that exists,.

**Comment by blmayer** [comment]
Nice, thanks for the suggestion. You can go ahead and create a PR if you want.

**Comment by blmayer** [comment]
Done in #17
