### ISSUE TITLE
printf: Illegal option

### ISSUE THREAD

**Issue by nicwaller** [blmayer/astro#18]
I'm trying astro for the first time, and when I load a page I get these error messages at the bottom:

```
Keys: qgrbosHmM, to see a description run astro -h./astro: 254: printf: Illegal option -
./astro: 254: printf: Illegal option -
./astro: 254: printf: Illegal option -
```

<details>
<summary>Screenshot</summary>
<img width="682" alt="image" src="https://user-images.githubusercontent.com/2850248/173741079-95b26ca5-df31-4e00-ba9f-1c5592d3f4ab.png">
</details>

## Steps to Reproduce

1. Using Ubuntu 22.04
2. Log into `/bin/bash` shell
3. `git clone https://github.com/blmayer/astro.git`
4. `git checkout f97bc206a69bd961ccbce814813d5ec98f1714a7`
5. `./astro gemini://derelict.garden/astro.gmi`

## What I attempted

I tried patching astro like this 👇  and the error went away.

```
diff --git a/astro b/astro
index 465bd79..9b454c4 100755
--- a/astro
+++ b/astro
@@ -251,7 +251,7 @@ EOF
                                        do
                                                printf "%*s" "$margin" ""
                                                # shellcheck disable=SC2059
-                                               printf "$sty$txt\\n"
+                                               printf "$sty $txt\\n"
                                        done
                                }
                        fi
```

However, that introduces an extra space on every line which may be unwanted.

**Comment by blmayer** [comment]
Hi Nic, thanks for opening this issue, I'll take a look into this issue briefly. I the meantime, please consider answering the following questions:

- Does this error happen to all websites or just this one?
- Do you have a custom configuration file?

And thanks for proposing a possible solution. If you figure it out feel free to open a pull request.

**Comment by nicwaller** [comment]
Oh hey, I just noticed that you fixed this bug. Thank you! I tried the new version and I no longer experience this bug. It makes the experience of using astro much better. 😃

**Comment by blmayer** [comment]
Thanks!
