### ISSUE TITLE
shell compatibility

### ISSUE THREAD

**Issue by rnwgnr** [blmayer/astro#32]
I'm in the works of preparing another PR and came across an ambiguity with the current implementation:
The shebang requests `/bin/sh` that will most probably be linked to a more powerful shell on most system (like bash).

Unfortunately astro at the moment won't work with `dash` - which seems to be the default link for `/bin/sh` on Debian-based systems.

Not sure how to tackle this - we could simply switch the shebang to `/bin/bash` or try to find out what breaks astro on dash.

What do you think?

**Comment by blmayer** [comment]
My goal is to be as close to POSIX compliance as possible, this way we ensure compatibility with most shells. My intention was to add an option at the start of astro, `set + ...` which forces POSIX only features, but I forgot.

**Comment by rnwgnr** [comment]
Thanks for the clarification - this will complicate things a bit :laughing: 
Need to revise my upcoming patch a bit :)
