### ISSUE TITLE
discussion: performance of astro

### ISSUE THREAD

**Issue by rnwgnr** [blmayer/astro#43]
Out of curiosity i started some investigation about performance bottlenecks of astro. I added a very basic [stopwatch function](https://github.com/rnwgnr/astro/blob/da9cf50f0fcf5bc2fb571306f6073176460bf51d/astro#L126) to get a first insight where the most time is spent. The output is stored in a "trace.XXXXXX" file in astro's cache folder.

A performance bottleneck that became obvious pretty fast are `sed` commands - especially sed commands that are called very often. This essentially boils down to `sed` in the `typesetgmi` function.

hardcore test is `geminispace.info/known-hosts` which at the time of writing sports over 2200 link lines.
Current main on my test machine:
```
url: gemini://geminispace.info:1965/known-hosts
openssl fetch took .172193728 seconds
status extract took .005172634 seconds
typeset took 24.502104686 seconds
```

[Replacing](https://github.com/rnwgnr/astro/blob/da9cf50f0fcf5bc2fb571306f6073176460bf51d/astro#L197) the 2 sed commands in the link rendering section of `typesetgmi` gets me down to:
```
typeset took 13.076992820 seconds
```

Even on a "normal page" like `station.martinrue.com` the difference is noticable. It gets down from 1.36 seconds to 0.93 seconds for me.

The current state of [the branch](https://github.com/rnwgnr/astro/tree/trace) has some drawbacks:
- the links page is not that easy to read
- the linkcounter is hardcoded as in "it is always there", but the appearance is still customizable

What do you think?

**Comment by blmayer** [comment]
Hi @rnwgnr, thanks for bringing this up, astro's performance bothers me too. I think the less we use pipelines, including sed ones the better. I like the initiative. Try to precompute styles when astro starts, leaving the minimum possible to be done while typesetting gmi, that's a guess.

Good job already, if you wish you can PR this and we work on the rest later.

Also, on line 212 there is a huge pipeline, it may be slow, we can output the transformed markup into a file and run `fold` in it.

**Comment by rnwgnr** [comment]
Since the custom renderer has been there, performance does not seem to be an issue anymore. Kudos for this implementation.
