### ISSUE TITLE
man page

### ISSUE THREAD

**Issue by rnwgnr** [blmayer/astro#48]
follow up to https://github.com/blmayer/astro/pull/47#issuecomment-1690564373 :
I thought about man pages as well.

I'd go with [scdoc](https://git.sr.ht/~sircmpwn/scdoc) for the raw format, example for a file can be found at: https://git.clttr.info/photo-stats/file/phosta.1.scd.html

**Comment by blmayer** [comment]
Interesting, but one thing I don't like about it is that we need a source file. In other projects I used [help2man](https://linux.die.net/man/1/help2man), it generates man pages using the --help from the command. So I only needed the improve a little the generated man page.

What do you think?

**Comment by rnwgnr** [comment]
Haven't used that till now, but the approach seems legit.

**Comment by blmayer** [comment]
Done in 631ce7063b1d748173d467115dc820fd19242728
