### ISSUE TITLE
bookmarks save in .cache?

### ISSUE THREAD

**Issue by guzzisti** [blmayer/astro#7]
Thanks for this amazing project...it perfectly fits the spirit of gemini. :)

It seems that bookmarks are currently saved in ~/.cache/astro/bookmarks.
For me it seems a bit odd to save the bookmarks in .cache which should be ephemeral, i'd rather expect it in ~/.config/... or ~/.local/...

What do you think?

**Comment by blmayer** [comment]
Hi guzzisti, thank you for the feedback!

I like the idea of ~/.config/... If you want you can make a PR and implement that.

Thanks.
